"""Init

Revision ID: 96a40767bd11
Revises: 
Create Date: 2024-09-04 17:59:34.459551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96a40767bd11'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Идентификатор объекта'),
    sa.Column('username', sa.String(), nullable=False, comment='Логин для входа'),
    sa.Column('name', sa.String(), nullable=True, comment='Имя пользователя'),
    sa.Column('surname', sa.String(), nullable=True, comment='Фамилия пользователя'),
    sa.Column('company', sa.String(), nullable=True, comment='Название компании'),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    schema='users'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users', schema='users')
    # ### end Alembic commands ###
